version: '3.8'

services:
  openethereum:
    image: openethereum/openethereum
    command: '--config dev --jsonrpc-interface=0.0.0.0'
    ports:
      - '8545:8545'
      - '8546:8546'
    volumes:
      - ./docker:/home/openethereum/.local/share
